import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import { Poppins } from "next/font/google";
import Providers from "./providers";
import "@rainbow-me/rainbowkit/styles.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          ::-webkit-scrollbar {
            display: none;
          }
          html, body {
            -ms-overflow-style: none;  /* IE and Edge */
            scrollbar-width: none;  /* Firefox */
          }
        `}</style>
      </head>
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} font-sans antialiased overflow-y-auto`}
      >
        <div className="bg-[#020113] text-white overflow-x-hidden"></div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
